format_version: v1.0
configName: pic32mx_pwm
folderName: pic32mx-pwm
frameworkPath: C:\projects\pic32mx-harmony\harmony-repo
processor: PIC32MX250F128B
projectName: pic32mx-pwm
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX250F128B.atdf
